---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dvm-sdk-rn-sample
  namespace: shopfully
  description: Sample integration of dvm-sdk-native into a react native app
  annotations:
    github.com/project-slug: 'wishabi/dvm-sdk-rn-sample'
    backstage.io/techdocs-ref: dir:../..
  tags:
    - frontend
    - mobile

spec:
  type: service
  owner: group:default/shopper-facing-digital-formats
  lifecycle: development